const API="https://graphql.anilist.co",K="yorumiru-v4.4.5",OLDK="yorumiru-v4.4.4";
let db=JSON.parse(localStorage.getItem(K)||localStorage.getItem(OLDK)||localStorage.getItem("yorumiru-v4")||'{"list":[],"favorites":[],"favChars":[],"profile":{"name":"Yorumiru User"}}'),genre="";
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])),save=()=>localStorage.setItem(K,JSON.stringify(db));
const Q=`query($search:String,$genre:String){Page(page:1,perPage:24){media(search:$search,genre:$genre,type:ANIME,isAdult:false,sort:[TRENDING_DESC,POPULARITY_DESC]){id title{romaji english}coverImage{large}bannerImage description episodes duration seasonYear averageScore genres status nextAiringEpisode{episode airingAt} airingSchedule(notYetAired:false,perPage:1,sort:TIME_DESC){nodes{episode airingAt}}characters(sort:ROLE,perPage:12){edges{node{id name{full}image{large}}}}relations{edges{relationType node{id title{romaji english}coverImage{large}episodes duration seasonYear status format}}}recommendations(perPage:6){nodes{mediaRecommendation{id title{romaji english}coverImage{large}episodes seasonYear}}}}}}`;
const DETAIL_Q=`query($id:Int){Media(id:$id,type:ANIME){id title{romaji english}coverImage{large}bannerImage description episodes duration seasonYear averageScore genres status format nextAiringEpisode{episode airingAt} airingSchedule(notYetAired:false,perPage:1,sort:TIME_DESC){nodes{episode airingAt}} characters(sort:ROLE,perPage:12){edges{node{id name{full}image{large}}}} relations{edges{relationType node{id title{romaji english}coverImage{large}bannerImage description episodes duration seasonYear status format nextAiringEpisode{episode airingAt} airingSchedule(notYetAired:false,perPage:1,sort:TIME_DESC){nodes{episode airingAt}}}}} recommendations(perPage:6){nodes{mediaRecommendation{id title{romaji english}coverImage{large}episodes seasonYear}}}}}`;
async function post(query,variables){const r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query,variables})});const j=await r.json();if(j.errors)throw new Error(j.errors[0]?.message||"API error");return j.data}
async function api(v){return (await post(Q,v)).Page.media}
async function getMedia(id){return (await post(DETAIL_Q,{id:Number(id)})).Media}
const title=m=>m.title?.english||m.title?.romaji||"Untitled";
const airedCount=m=>{const next=Number(m.nextAiringEpisode?.episode);if(next>1)return next-1;const latest=Number(m.airingSchedule?.nodes?.[0]?.episode);if(latest>0)return latest;return Number(m.episodes)||0};
const displayEpisodes=m=>{const aired=airedCount(m),total=Number(m.episodes)||0;if(m.status==="RELEASING"&&aired>0)return total>aired?`${aired}/${total}`:`${aired}`;return total||aired||"?"};
function card(m){let e=document.createElement("article");e.className="card";e.innerHTML=`<div class=poster><img src="${esc(m.coverImage?.large||"")}"></div><div class=body><div class=title>${esc(title(m))}</div><div class=meta>${m.seasonYear||""} · ${displayEpisodes(m)} eps</div></div>`;e.onclick=()=>openAnime(m);return e}
async function feed(){let rows=[];try{rows=await api({search:$("#q").value.trim()||null,genre:genre||null})}catch{};$("#feed").innerHTML="";rows.forEach(m=>$("#feed").append(card(m)))}
const genres=["All","Action","Adventure","Comedy","Drama","Fantasy","Horror","Romance","Sci-Fi","Sports","Thriller"];
$("#genres").innerHTML=genres.map(g=>`<button data-g="${g==="All"?"":g}">${g}</button>`).join("");document.querySelector("#genres button").classList.add("active");
$("#genres").onclick=e=>{if(e.target.tagName==="BUTTON"){genre=e.target.dataset.g;document.querySelectorAll("#genres button").forEach(b=>b.classList.toggle("active",b.dataset.g===genre));feed()}};$("#q").oninput=()=>feed();$("#search").onclick=()=>$("#q").focus();

// Build one franchise page from linked PREQUEL/SEQUEL entries instead of treating every season as a separate anime.
const SERIES_FORMATS=new Set(["TV","ONA","TV_SHORT"]);
async function collectFranchise(start){
  const seen=new Map(),queue=[Number(start.id)];
  while(queue.length&&seen.size<14){const id=queue.shift();if(seen.has(id))continue;let m;try{m=id===Number(start.id)?start:await getMedia(id)}catch{continue}seen.set(id,m);for(const e of (m.relations?.edges||[])){if(!["PREQUEL","SEQUEL"].includes(e.relationType))continue;const n=e.node;if(!n?.id||!SERIES_FORMATS.has(n.format))continue;if(!seen.has(Number(n.id)))queue.push(Number(n.id))}}
  let members=[...seen.values()];
  if(members.length<2)return {root:start,members:[start]};
  members.sort((a,b)=>(Number(a.seasonYear)||9999)-(Number(b.seasonYear)||9999)||Number(a.id)-Number(b.id));
  return {root:members[0],members};
}
function seasonLabel(m,i){const t=title(m);let extra="";if(/final season/i.test(t))extra=" — The Final Season";else if(i>0&&/season\s*\d+/i.test(t)){const match=t.match(/season\s*\d+(.*)$/i);if(match&&match[1])extra=match[1].replace(/[():-]/g," ").trim()?` — ${match[1].replace(/[():-]/g," ").trim()}`:""}return `Season ${i+1}${extra}`}
function normalizeSeriesWatch(root,members){
  const ids=new Set(members.map(m=>Number(m.id)));let existing=db.list.filter(x=>ids.has(Number(x.id))||ids.has(Number(x.seriesId)));
  let seriesId=Number(root.id);let combined={id:seriesId,seriesId,data:root,members:members.map(m=>m.id),seasons:[],last:existing.reduce((n,x)=>Math.max(n,Number(x.last)||0),0)||Date.now()};
  members.forEach((m,i)=>{let old=existing.find(x=>Number(x.id)===Number(m.id))||existing.find(x=>Number(x.seriesId)===Number(m.id));let count=Math.max(airedCount(m),Number(m.episodes)||0);let eps=old?.seasons?.flatMap(s=>s.episodes||[])||[];eps=Array.from({length:count},(_,j)=>!!eps[j]);combined.seasons.push({name:seasonLabel(m,i),mediaId:m.id,episodes:eps,data:m})});
  db.list=db.list.filter(x=>!existing.includes(x));db.list.push(combined);save();return combined}
function findSeriesRecord(root,members){const ids=new Set(members.map(m=>Number(m.id)));return db.list.find(x=>ids.has(Number(x.id))||ids.has(Number(x.seriesId)))}

async function openAnime(m){
  try{
    const family=await collectFranchise(m);const root=family.root,members=family.members;const record=findSeriesRecord(root,members);const item=record||null;const chars=root.characters?.edges||[];const recs=(root.recommendations?.nodes||[]).map(x=>x.mediaRecommendation).filter(Boolean);
    const seasons=members.map((n,i)=>({name:seasonLabel(n,i),episodes:airedCount(n),total:Number(n.episodes)||0,id:n.id,media:n}));
    $("#anime").innerHTML=`<button class=x onclick="animeDlg.close()">×</button><div class=detailBanner><img src="${esc(root.bannerImage||root.coverImage?.large||"")}"></div><div class=detailHead><div class=detailPoster><img src="${esc(root.coverImage?.large||"")}"></div><div><h1>${esc(title(root))}</h1><div class=muted>${root.seasonYear||""} · ${root.status||""} · ${root.duration||"?"} min/ep</div></div></div><button class=primary id=add>${item?"In watchlist":"＋ Add to watchlist"}</button><button class="secondary fav" id="fav">${db.favorites.includes(root.id)?"♥ Favorited":"♡ Favorite"}</button><section><h3>About</h3><p class=muted>${strip(root.description)||"No description available."}</p></section><section><h3>Characters</h3><div class=chars>${chars.map(c=>`<div class=cmini><img src="${esc(c.node.image?.large||"")}"><small>${esc(c.node.name.full)}</small></div>`).join("")}</div></section><section><h3>Seasons</h3>${seasons.map((s,i)=>`<div class=season data-s="${i}"><span>${esc(s.name)}<br><small class=muted>${s.episodes||"?"}${s.total&&s.total>s.episodes?` of ${s.total}`:""} eps available</small></span>›</div>`).join("")}</section><section><h3>Similar anime</h3><div class=similar>${recs.map(x=>`<div class=sim data-id="${x.id}"><img src="${esc(x.coverImage?.large||"")}"><b>${esc(title(x))}</b></div>`).join("")}</div></section><section><h3>Comments</h3><div class=muted>Comments will become shared with the account system.</div></section>`;
    $("#add").onclick=()=>addSeries(root,members);$("#fav").onclick=()=>toggleFavorite(root,members);
    document.querySelectorAll(".season").forEach(s=>s.onclick=()=>openEpisodesFamily(root,members,+s.dataset.s));
    document.querySelectorAll(".sim").forEach(s=>s.onclick=async()=>{try{const r=await getMedia(s.dataset.id);animeDlg.close();openAnime(r)}catch{}});
    animeDlg.showModal();
  }catch(err){console.error(err);animeDlg.showModal()}
}
function strip(x){return String(x||"").replace(/<[^>]*>/g,"").slice(0,500)}
function addSeries(root,members){let rec=normalizeSeriesWatch(root,members);$("#add").textContent="In watchlist";renderWatch();return rec}
function toggleFavorite(root,members){const ids=members.map(m=>Number(m.id));const exists=db.favorites.includes(Number(root.id));if(exists)db.favorites=db.favorites.filter(id=>!ids.includes(Number(id)));else db.favorites.push(Number(root.id));save();$("#fav").textContent=exists?"♡ Favorite":"♥ Favorited";profile()}
function openEpisodesFamily(root,members,si){let rec=findSeriesRecord(root,members)||normalizeSeriesWatch(root,members);let s=rec.seasons[si];let m=s.data||members[si],eps=s.episodes||[];let count=Math.max(airedCount(m),Number(m.episodes)||0);if(eps.length<count){eps.push(...Array(count-eps.length).fill(false));s.episodes=eps;save()}
  $("#eps").innerHTML=`<button class=x onclick="epDlg.close()">×</button><h2>${esc(title(root))} — ${esc(s.name)}</h2><button class=secondary id=all>${eps.length&&eps.every(Boolean)?"Unmark season":"Mark full season watched"}</button><div>${eps.map((d,i)=>`<div class="episode ${d?"done":""}" data-i="${i}"><div class=num>${d?"✓":i+1}</div><div><b>Episode ${i+1}</b><div class=muted>${m.duration||root.duration||"?"} min</div></div><span>${d?"WATCHED":"›"}</span></div>`).join("")}</div>`;
  $("#all").onclick=()=>{eps.fill(!eps.every(Boolean));rec.last=Date.now();save();openEpisodesFamily(root,members,si);renderWatch()};
  document.querySelectorAll(".episode").forEach(e=>e.onclick=()=>{let i=+e.dataset.i;if(!eps[i]){let missing=eps.slice(0,i).some(v=>!v);if(missing){if(confirm(`Have you watched all episodes up to Episode ${i+1}?\nOK = mark 1–${i+1}.\nCancel = only Episode ${i+1}.`))eps.fill(true,0,i+1);else eps[i]=true}else eps[i]=true}else eps[i]=false;rec.last=Date.now();save();openEpisodesFamily(root,members,si);renderWatch()});epDlg.showModal()}

function renderWatch(){let tab=document.querySelector("[data-tab].active")?.dataset.tab||"list";if(tab==="upcoming"){const upcoming=db.list.flatMap(x=>{const members=(x.members||[]).map(id=>x.seasons.find(s=>Number(s.mediaId)===Number(id))?.data).filter(Boolean);const all=members.length?members:[x.data];return all.map(m=>m?.nextAiringEpisode?{x,m,a:m.nextAiringEpisode}:null).filter(Boolean)}).sort((a,b)=>a.a.airingAt-b.a.airingAt);$("#watchContent").innerHTML=upcoming.length?`<section><b>UPCOMING EPISODES</b>${upcoming.map(({x,m,a})=>`<div class=watch data-id="${x.id}"><div class=thumb><img src="${esc(m.coverImage?.large||x.data.coverImage?.large||"")}"></div><div><b>${esc(title(x.data))}</b><div class=muted>${esc(seasonNameFor(x,m))} · Episode ${a.episode}</div><div class=muted>${new Date(a.airingAt*1000).toLocaleString()}</div></div></div>`).join("")}</section>`:"<p class=muted>No upcoming episodes found for your watchlist.</p>";return}let w=db.list.filter(x=>{let e=x.seasons.flatMap(s=>s.episodes||[]);return e.some(Boolean)&&!e.every(Boolean)}).sort((a,b)=>(b.last||0)-(a.last||0)),p=db.list.filter(x=>x.seasons.flatMap(s=>s.episodes||[]).every(v=>!v));$("#watchContent").innerHTML=rows("WATCHING",w)+rows("PLAN TO WATCH",p)}
function seasonNameFor(x,m){const s=x.seasons.find(s=>Number(s.mediaId)===Number(m.id));return s?.name||"Upcoming"}
function rows(h,a){return`<section><b>${h}</b>${a.length?a.map(x=>{let e=x.seasons.flatMap(s=>s.episodes||[]),w=e.filter(Boolean).length;return`<div class=watch data-id="${x.id}"><div class=thumb><img src="${esc(x.data.coverImage?.large||"")}"></div><div><b>${esc(title(x.data))}</b><div class=muted>${w}/${e.length} episodes</div><div class=bar><i style="width:${e.length?w/e.length*100:0}%"></i></div></div></div>`}).join(""):"<p class=muted>Nothing here yet.</p>"}</section>`}
function profile(){let w=db.list.reduce((n,x)=>n+x.seasons.flatMap(s=>s.episodes||[]).filter(Boolean).length,0);let mins=db.list.reduce((n,x)=>n+x.seasons.flatMap(s=>s.episodes||[]).filter(Boolean).length*(x.data.duration||24),0);$("#episodes").textContent=w;$("#hours").textContent=Math.round(mins/60)+"h";$("#username").textContent=db.profile.name;$("#favShows").innerHTML=db.list.filter(x=>db.favorites.includes(x.id)).map(x=>`<div class=mini><img src="${esc(x.data.coverImage?.large||"")}"><b>${esc(title(x.data))}</b></div>`).join("")||"<span class=muted>No favorites yet.</span>";$("#favChars").innerHTML=db.favChars.map(c=>`<div class=char><img src="${esc(c.image||"")}"><small>${esc(c.name)}</small></div>`).join("")||"<span class=muted>Add characters you like.</span>";$("#collection").innerHTML=["Watching","Completed","Plan to Watch"].map((n,i)=>`<div class=season><span>${n}</span><b>${count(i)}</b></div>`).join("")}
function count(i){return db.list.filter(x=>{let e=x.seasons.flatMap(s=>s.episodes||[]);return i===0?e.some(Boolean)&&!e.every(Boolean):i===1?e.length&&e.every(Boolean):e.every(v=>!v)}).length}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$("#"+b.dataset.page).classList.add("active");document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n===b));if(b.dataset.page==="watch")renderWatch();if(b.dataset.page==="profile")profile()});
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderWatch()});
$("#dots").onclick=()=>{$("#name").value=db.profile.name;settingsDlg.showModal()};$("#save").onclick=()=>{db.profile.name=$("#name").value.trim()||"Yorumiru User";save();settingsDlg.close();profile()};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());
document.addEventListener("click",e=>{let r=e.target.closest(".watch");if(r){let x=db.list.find(z=>z.id==r.dataset.id);if(x)openAnime(x.data)}});feed();renderWatch();profile();
