const API="https://graphql.anilist.co",K="yorumiru-v4";let db=JSON.parse(localStorage.getItem(K)||'{"list":[],"favorites":[],"favChars":[],"profile":{"name":"Yorumiru User"}}'),genre="";
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])),save=()=>localStorage.setItem(K,JSON.stringify(db));
const Q=`query($search:String,$genre:String){Page(page:1,perPage:24){media(search:$search,genre:$genre,type:ANIME,isAdult:false,sort:[TRENDING_DESC,POPULARITY_DESC]){id title{romaji english}coverImage{large}bannerImage description episodes duration seasonYear averageScore genres status nextAiringEpisode{episode airingAt}characters(sort:ROLE,perPage:12){edges{node{id name{full}image{large}}}}relations{edges{relationType node{id title{romaji english}coverImage{large}episodes seasonYear}}}recommendations(perPage:6){nodes{mediaRecommendation{id title{romaji english}coverImage{large}episodes seasonYear}}}}}}`;
async function api(v){let r=await fetch(API,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({query:Q,variables:v})});return(await r.json()).data.Page.media}
const title=m=>m.title.english||m.title.romaji;
function card(m){let e=document.createElement("article");e.className="card";e.innerHTML=`<div class=poster><img src="${esc(m.coverImage?.large||"")}"></div><div class=body><div class=title>${esc(title(m))}</div><div class=meta>${m.seasonYear||""} · ${m.episodes||"?"} eps</div></div>`;e.onclick=()=>openAnime(m);return e}
async function feed(){let rows=[];try{rows=await api({search:$("#q").value.trim()||null,genre:genre||null})}catch{};$("#feed").innerHTML="";rows.forEach(m=>$("#feed").append(card(m)))}
const genres=["All","Action","Adventure","Comedy","Drama","Fantasy","Horror","Romance","Sci-Fi","Sports","Thriller"];$("#genres").innerHTML=genres.map(g=>`<button data-g="${g==="All"?"":g}">${g}</button>`).join("");document.querySelector("#genres button").classList.add("active");
$("#genres").onclick=e=>{if(e.target.tagName==="BUTTON"){genre=e.target.dataset.g;document.querySelectorAll("#genres button").forEach(b=>b.classList.toggle("active",b.dataset.g===genre));feed()}};$("#q").oninput=()=>feed();$("#search").onclick=()=>{$("#q").focus()};
function openAnime(m){let item=db.list.find(x=>x.id===m.id),chars=m.characters?.edges||[],recs=(m.recommendations?.nodes||[]).map(x=>x.mediaRecommendation).filter(Boolean);let seasons=[{name:"Season 1",episodes:m.episodes||0}];m.relations?.edges?.filter(x=>x.relationType==="SEQUEL").forEach((x,i)=>seasons.push({name:`Season ${i+2}`,episodes:x.node.episodes||0,id:x.node.id}));$("#anime").innerHTML=`<button class=x onclick="animeDlg.close()">×</button><div class=detailBanner><img src="${esc(m.bannerImage||m.coverImage?.large||"")}"></div><div class=detailHead><div class=detailPoster><img src="${esc(m.coverImage?.large||"")}"></div><div><h1>${esc(title(m))}</h1><div class=muted>${m.seasonYear||""} · ${m.status||""} · ${m.duration||"?"} min/ep</div></div></div><button class=primary id=add>${item?"In watchlist":"＋ Add to watchlist"}</button><section><h3>About</h3><p class=muted>${strip(m.description)||"No description available."}</p></section><section><h3>Characters</h3><div class=chars>${chars.map(c=>`<div class=cmini><img src="${esc(c.node.image?.large||"")}"><small>${esc(c.node.name.full)}</small></div>`).join("")}</div></section><section><h3>Seasons</h3>${seasons.map((s,i)=>`<div class=season data-s="${i}"><span>${s.name}<br><small class=muted>${s.episodes||"?"} episodes</small></span>›</div>`).join("")}</section><section><h3>Similar anime</h3><div class=similar>${recs.map(x=>`<div class=sim data-id="${x.id}"><img src="${esc(x.coverImage?.large||"")}"><b>${esc(title(x))}</b></div>`).join("")}</div></section><section><h3>Comments</h3><div class=muted>Comments will become shared with the account system.</div></section>`;$("#add").onclick=()=>add(m);document.querySelectorAll(".season").forEach(s=>s.onclick=()=>openEpisodes(m,+s.dataset.s));animeDlg.showModal()}
function strip(x){return String(x||"").replace(/<[^>]*>/g,"").slice(0,500)}
function add(m){if(!db.list.some(x=>x.id===m.id)){db.list.push({id:m.id,data:m,seasons:[{name:"Season 1",episodes:Array(m.episodes||0).fill(false)}],last:Date.now()});save()}$("#add").textContent="In watchlist";renderWatch()}
function openEpisodes(m,si){let x=db.list.find(z=>z.id===m.id);if(!x){add(m);x=db.list.find(z=>z.id===m.id)}let eps=x.seasons[si]?.episodes||Array(m.episodes||0).fill(false);if(!x.seasons[si])x.seasons[si]={name:"Season "+(si+1),episodes:eps};$("#eps").innerHTML=`<button class=x onclick="epDlg.close()">×</button><h2>${esc(title(m))} — Season ${si+1}</h2><button class=secondary id=all>${eps.length&&eps.every(Boolean)?"Unmark season":"Mark full season watched"}</button><div>${eps.map((d,i)=>`<div class="episode ${d?"done":""}" data-i="${i}"><div class=num>${d?"✓":i+1}</div><div><b>Episode ${i+1}</b><div class=muted>${m.duration||"?"} min</div></div><span>${d?"WATCHED":"›"}</span></div>`).join("")}</div>`;$("#all").onclick=()=>{eps.fill(!eps.every(Boolean));x.last=Date.now();save();openEpisodes(m,si)};document.querySelectorAll(".episode").forEach(e=>e.onclick=()=>{let i=+e.dataset.i;if(!eps[i]){let missing=eps.slice(0,i).some(v=>!v);if(missing){if(confirm(`Have you watched all episodes up to Episode ${i+1}?\nOK = mark 1–${i+1}.\nCancel = only Episode ${i+1}.`))eps.fill(true,0,i+1);else eps[i]=true}else eps[i]=true}else eps[i]=false;x.last=Date.now();save();openEpisodes(m,si);renderWatch()});epDlg.showModal()}
function renderWatch(){let tab=document.querySelector("[data-tab].active")?.dataset.tab||"list";if(tab==="upcoming"){$("#watchContent").innerHTML="<p class=muted>Upcoming episodes from your watchlist will appear here when airing dates are available.</p>";return}let w=db.list.filter(x=>{let e=x.seasons.flatMap(s=>s.episodes);return e.some(Boolean)&&!e.every(Boolean)}).sort((a,b)=>b.last-a.last),p=db.list.filter(x=>x.seasons.flatMap(s=>s.episodes).every(v=>!v));$("#watchContent").innerHTML=rows("WATCHING",w)+rows("PLAN TO WATCH",p)}
function rows(h,a){return`<section><b>${h}</b>${a.length?a.map(x=>{let e=x.seasons.flatMap(s=>s.episodes),w=e.filter(Boolean).length;return`<div class=watch data-id="${x.id}"><div class=thumb><img src="${esc(x.data.coverImage?.large||"")}"></div><div><b>${esc(title(x.data))}</b><div class=muted>${w}/${e.length} episodes</div><div class=bar><i style="width:${e.length?w/e.length*100:0}%"></i></div></div></div>`}).join(""):"<p class=muted>Nothing here yet.</p>"}</section>`}
function profile(){let w=db.list.reduce((n,x)=>n+x.seasons.flatMap(s=>s.episodes).filter(Boolean).length,0);let mins=db.list.reduce((n,x)=>n+x.seasons.flatMap(s=>s.episodes).filter(Boolean).length*(x.data.duration||24),0);$("#episodes").textContent=w;$("#hours").textContent=Math.round(mins/60)+"h";$("#username").textContent=db.profile.name;$("#favShows").innerHTML=db.list.filter(x=>db.favorites.includes(x.id)).map(x=>`<div class=mini><img src="${esc(x.data.coverImage?.large||"")}"><b>${esc(title(x.data))}</b></div>`).join("")||"<span class=muted>No favorites yet.</span>";$("#favChars").innerHTML=db.favChars.map(c=>`<div class=char><img src="${esc(c.image||"")}"><small>${esc(c.name)}</small></div>`).join("")||"<span class=muted>Add characters you like.</span>";$("#collection").innerHTML=["Watching","Completed","Plan to Watch"].map((n,i)=>`<div class=season><span>${n}</span><b>${count(i)}</b></div>`).join("")}
function count(i){return db.list.filter(x=>{let e=x.seasons.flatMap(s=>s.episodes);return i===0?e.some(Boolean)&&!e.every(Boolean):i===1?e.length&&e.every(Boolean):e.every(v=>!v)}).length}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>{document.querySelectorAll(".page").forEach(p=>p.classList.remove("active"));$("#"+b.dataset.page).classList.add("active");document.querySelectorAll(".nav").forEach(n=>n.classList.toggle("active",n===b));if(b.dataset.page==="watch")renderWatch();if(b.dataset.page==="profile")profile()});
document.querySelectorAll("[data-tab]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-tab]").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderWatch()});
$("#dots").onclick=()=>{$("#name").value=db.profile.name;settingsDlg.showModal()};$("#save").onclick=()=>{db.profile.name=$("#name").value.trim()||"Yorumiru User";save();settingsDlg.close();profile()};document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>$(b.dataset.close).close());
document.addEventListener("click",e=>{let r=e.target.closest(".watch");if(r){let x=db.list.find(z=>z.id==r.dataset.id);if(x)openAnime(x.data)}});feed();renderWatch();profile();